import 'package:ecommerce_app/model/product.dart';

class MyProduct {
  static List<Product> allProducts = [
    Product(
        0,
        'All Back',
        'Latest style',
        'Clean styling with all braiding facing backward',
        'assets/images/sty1.png',
        200.0,
      0,
      150.0,
      [
        'assets/images/sty1.png',
        'assets/images/sty2.png',
        'assets/images/sty4.png',
        'assets/images/caro3.png'
      ],

        ),
    Product(
        2,
        'Tousled Lob Haircut',
        'Coloring trends',
        'If you want that glamorous edge that a crop can give but with the flexibility of longer locks, then a lob haircut is a perfect choice.',
        'assets/images/sty2.png',
        500,
       1,
      400,
      [ 'assets/images/caro4.png',
        'assets/images/caro5.png',
        ('assets/images/caro6.png'),
        ('assets/images/caro7.png'),]
    ),
    Product(
        3,
        'Curtain Bangs and Shag Haircut',
        'British cut',
        'A fringe is a thing to puzzle over. In 2024 bangs are on-trend, so a shag with curtain bangs can be one of the best haircuts to try asap. Don’t want to regret it? Try clip-in bangs and then make the final decision.',
        'assets/images/sty3.png',
        300,
        0,
    200,
        [ ('assets/images/caro7.png'),
          ('assets/images/caro8.png'),
          ('assets/images/caro9.png'),
          ('assets/images/caro10.png'),]
    ),
    Product(
        0,
        'Wavy Cut with Curtain Bangs',
        'Brown girl',
        'This is one of the most fascinating trending hairstyles for women of any age. The face-framing bangs make your cheekbones appear more prominent and elongate your face. The shoulder-length layered loose waves contribute to the statement look.',
        'assets/images/sty4.png',
        350,
        1,
        250,
        [ ('assets/images/caro1.png'),
          ('assets/images/caro.png'),
         ( 'assets/images/caro2.png'),
         ( 'assets/images/caro3.png'),]),
    Product(
        5,
        'Textured Haircut.',
        'white British',
        'Another great way to take advantage of short bob haircuts without high maintenance is to try a textured look. The quickest way to style a trendy bob is to make it a bit messy and tousled.',
        'assets/images/sty5.png',
        390,
        1,
    300,
        [ ('assets/images/caro4.png'),
          ('assets/images/caro5.png'),
          ('assets/images/caro6.png'),
          ('assets/images/caro7.png'),]),
    Product(
        0,
        'Lob with Face-Framing Bangs',
        'Brown Braid',
        'A voluminous lob is one of the trendiest haircuts for women, and it looks so charming with long face-framing bangs. If you have dark brown hair, just add some subtle highlights to create a lively, romantic look.',
        'assets/images/sty9.png',
        500,
        1, 400,
        [ ('assets/images/abaya.png'),
          ('assets/images/abaya1.png'),
          ('assets/images/abaya3.png'),
          ('assets/images/abaya4.png'),]),
    Product(
        1,
        'Cornrow braids',
        'Latest style',
        'This popular hairstyle is a winning choice for both short and long hair, and for both Black women and men. The braids are typically thin and lie very close to the head. Cornrows also offer plenty of options for patterns as the braids are guided by how your hair is parted.You can experiment with other hair braiding styles using cornrows as the foundation. Some of these looks include lemonade braids, soft locs, Ghana braids, faux locs, knotless braids, goddess braids, and crochet braids. No matter your aesthetic, cornrow braids will keep your hair healthy and you feeling your best. ',
        'assets/images/sty7.png',
        200.0,
        1,120,
        [ ('assets/images/saudi.png'),
          ('assets/images/saudi1.png'),
          ('assets/images/saudi3.jpg'),
          ('assets/images/saudi2.jpg'),]),
    Product(
        2,
        'Box braids',
        'Coloring trends',
        'Box braids are not only a protective, low-maintenance way to wear your hair, but they’re also deeply rooted in Black history. Their origins go back as far as 3500 B.C. The name itself is due to the distinct box-shaped part at the root of each one of these three-strand braids. You can wear box braids long and loose, pulled back into a braided bun or ponytail, or even styled as a half-up, half-down look. If you’re having trouble deciding on the thickness of each plait or if you’re interested in adding extensions, you can talk to a braider to get their expert opinion.',
        'assets/images/sty8.png',
        500,
        1,200, [ ('assets/images/saudi.png'),
      ('assets/images/saudi1.png'),
      ('assets/images/saudi3.jpg'),
      ('assets/images/saudi2.jpg'),]),
    Product(
        3,
        'Triangle box braids',
        'Nigerian cut',
        'You’ll still get free-flowing locks with this style, but there is a noticeable difference in how the hair is sectioned off with this slightly tweaked version of box braids. A simple change in part — from box to triangle — makes a big difference and gives this classic look an edgier upgrade. Play around with braid thickness, side and center parts, or even hair color to make this style all your own. Chalia Mangrum, an Ohio-based braider, calls triangle box braids a trend suitable for a wide variety of hair textures. Like the regular box braid, you can be creative with how you style the plaits. Box braids can last between four and six weeks with proper care.',
        'assets/images/sty9.png',
        300,
        1,200, [ ('assets/images/saudi.png'),
     ( 'assets/images/saudi1.png'),
      ('assets/images/saudi3.jpg'),
      ('assets/images/saudi2.jpg'),]),
    Product(
        4,
        'Senegalese twists',
        'Brown girl',
        'If your hair could use a break from daily styling and the excess use of hot styling tools, Senegalese twists are a stunning way to look after your hair and promote hair growth.To create these types of braids, synthetic or human hair is attached to the root of your natural hair, separated into two strands, and wrapped all the way down each hair shaft. The result?  Sleek-looking twists that can be swept to the side or pinned back. They offer a slightly different texture than a classic three-strand braid. ',
        'assets/images/sty10.png',
        350,
        1,250,
        [ ('assets/images/men.png'),
          ('assets/images/women.png'),
         ( 'assets/images/boy.png'),
         ( 'assets/images/girl.png'),]),
    Product(
        5,
        'Nubian twists',
        'Eygtiant Queen',
        'The Nubian twist is another style with origins that can be traced as far back as ancient Egypt. The installation process is somewhat similar to that of the Senegalese twist, but the result is quite different — specifically in terms of texture and length.Tight coils are the most obvious visual difference between these twist braids and the Senegalese alternative. You’ll also find Nubian twists worn with shorter hairstyles, often resting just above the shoulder.  ',
        'assets/images/sty11.png',
        390,
        1,300, [ ('assets/images/caro.png'),
      ('assets/images/caro1.png'),
      ('assets/images/caro2.png'),
     ( 'assets/images/caro9.png'),]),
    Product(
        6,
        'LMicro braids',
        'Brown Braid',
        'Of all the different types of braids for Black women, this braiding style may not look much like a braid at all. In contrast to the varying thickness of cornrows and box braids, micro braids are always created using very small sections of hair. This results in plaits that look and feel more like a thick strand of hair rather than interlaced braids. ',
        'assets/images/sty12.png',
        500,
        1,450,  [ ('assets/images/sty1.png'),
      ('assets/images/sty2.png'),
     ( 'assets/images/sty3.png'),
      ('assets/images/sty4.png'),]),
    Product(
        6,
        'Fulani braids',
        'Brown Braid',
        'Fulani braids are one of many tribal African braid styles that have become more mainstream. These are characterized by just one straight-back braid paired with others that flow in opposite directions across the crown of your head, often toward your ears or temples. The intricacy and beauty of this look make it one of the more popular styles of braids for Black women. Another appealing detail of Fulani braids is the combination of scalp-hugging cornrows on the top and the volumizing effect of box braids in the back. Feel free to get creative with this style by adding curls, extensions, or a pop of brightly colored beads. ',
        'assets/images/sty13.png',
        500,
        1,300,
        [ ('assets/images/sty1.png'),
          ('assets/images/sty2.png'),
        (  'assets/images/sty3.png'),
          ('assets/images/sty4.png'),]),
    Product(
        1,
        'Boho stitch braids',
        'Latest style',
        'This hairstyle is a combination of boho and stitch braids. Think of it as an extra way of rocking stitch braids.',
        'assets/images/sty14.png',
        200.0,
        1,100, [( 'assets/images/sty1.png'),
      ('assets/images/sty2.png'),
      ('assets/images/sty3.png'),
      ('assets/images/sty4.png'),]),
    Product(
        2,
        'Cornrows',
        'Coloring trends',
        'Cornrows are a lifesaver, especially when you don’t want to do too much with your hair. You can even do it yourself if you have the time.',
        'assets/images/sty10.png',
        500,
        0,400, [( 'assets/images/sty4.png'),
      ('assets/images/sty5.png'),
      ('assets/images/sty6.png'),
      ('assets/images/sty9.png'),]),
    Product(
        3,
        'Bantu knots with curls',
        'Nigerian cut',
        'Bantu knots has been around for a while and is always a hit.',
        'assets/images/sty12.png',
        300,
        1,200, [ ('assets/images/sty1.png'),
      ('assets/images/sty10.png'),
      ('assets/images/sty3.png'),
      ('assets/images/sty12.png'),]),
    Product(
        4,
        'Two-row cornrows',
        'Brown girl',
        'Before you roll your eyes and ask, “Cornrows again?” Listen, cornrows are simple, affordable, classy and versatile. They also don’t look like your regular cornrows.',
        'assets/images/sty9.png',
        350,
        1,200,[ 'assets/images/caro.png',
      'assets/images/caro1.png',
      'assets/images/caro2.png',
      'assets/images/caro9.png',]),
    Product(
        5,
        'Zigzag braids with beads',
        'Eygtiant Queen',
        'The curls give a fresh breath of life to hairstyles that would have been better left in 2000 and this ZigZag braid is proof.',
        'assets/images/sty9.png',
        390,
        1,200, [ ('assets/images/sty1.png'),
      ('assets/images/sty8.png'),
      ('assets/images/sty13.png'),
     ( 'assets/images/sty4.png'),]),
    Product(
        6,
        'Starter locs',
        'Brown Braid',
        'For when you’re just starting on your loc journey.',
        'assets/images/sty11.png',
        500,
        1,430, [ ('assets/images/sty1.png'),
      ('assets/images/sty2.png'),
    (  'assets/images/sty3.png'),
      ('assets/images/sty4.png'),]),
    Product(
        7,
        'Bantu locs',
        'Brown Braid',
        'Who says you can’t rock your bantu knots because your hair is locked? ',
        'assets/images/sty14.png',
        500,
        1,430, [ ('assets/images/boy.png'),
      ('assets/images/girl.png'),
      ('assets/images/man.png'),
      ('assets/images/woman.png'),])
  ];
  static List<Product> africaBraid = [
    Product(
        1,
        'Cornrow braids',
        'Latest style',
        'This popular hairstyle is a winning choice for both short and long hair, and for both Black women and men. The braids are typically thin and lie very close to the head. Cornrows also offer plenty of options for patterns as the braids are guided by how your hair is parted.You can experiment with other hair braiding styles using cornrows as the foundation. Some of these looks include lemonade braids, soft locs, Ghana braids, faux locs, knotless braids, goddess braids, and crochet braids. No matter your aesthetic, cornrow braids will keep your hair healthy and you feeling your best. ',
        'assets/images/sty7.png',
        200.0,
        0,100, [ 'assets/images/saudi.png',
      'assets/images/saudi7.png',
      'assets/images/saudi5.jpg',
      'assets/images/saudi4.png',]),
    Product(
        2,
        'Box braids',
        'Coloring trends',
        'Box braids are not only a protective, low-maintenance way to wear your hair, but they’re also deeply rooted in Black history. Their origins go back as far as 3500 B.C. The name itself is due to the distinct box-shaped part at the root of each one of these three-strand braids. You can wear box braids long and loose, pulled back into a braided bun or ponytail, or even styled as a half-up, half-down look. If you’re having trouble deciding on the thickness of each plait or if you’re interested in adding extensions, you can talk to a braider to get their expert opinion.',
        'assets/images/sty8.png',
        500,
        1,350, [ 'assets/images/sty1.png',
      'assets/images/sty12.png',
      'assets/images/sty13.png',
      'assets/images/sty14.png',]),
    Product(
        3,
        'Triangle box braids',
        'Nigerian cut',
        'You’ll still get free-flowing locks with this style, but there is a noticeable difference in how the hair is sectioned off with this slightly tweaked version of box braids. A simple change in part — from box to triangle — makes a big difference and gives this classic look an edgier upgrade. Play around with braid thickness, side and center parts, or even hair color to make this style all your own. Chalia Mangrum, an Ohio-based braider, calls triangle box braids a trend suitable for a wide variety of hair textures. Like the regular box braid, you can be creative with how you style the plaits. Box braids can last between four and six weeks with proper care.',
        'assets/images/sty9.png',
        300,
        1,230, [ 'assets/images/caro.png',
      'assets/images/caro1.png',
      'assets/images/caro2.png',
      'assets/images/caro3.png',]),
    Product(
        4,
        'Senegalese twists',
        'Brown girl',
        'If your hair could use a break from daily styling and the excess use of hot styling tools, Senegalese twists are a stunning way to look after your hair and promote hair growth.To create these types of braids, synthetic or human hair is attached to the root of your natural hair, separated into two strands, and wrapped all the way down each hair shaft. The result?  Sleek-looking twists that can be swept to the side or pinned back. They offer a slightly different texture than a classic three-strand braid. ',
        'assets/images/sty10.png',
        350,
        1,300, [ 'assets/images/caro8.png',
      'assets/images/caro9.png',
      'assets/images/caro9.png',
      'assets/images/caro10.png',]),
    Product(
        5,
        'Nubian twists',
        'Eygtiant Queen',
        'The Nubian twist is another style with origins that can be traced as far back as ancient Egypt. The installation process is somewhat similar to that of the Senegalese twist, but the result is quite different — specifically in terms of texture and length.Tight coils are the most obvious visual difference between these twist braids and the Senegalese alternative. You’ll also find Nubian twists worn with shorter hairstyles, often resting just above the shoulder.  ',
        'assets/images/sty11.png',
        390,
        1,200, [ 'assets/images/sty1.png',
      'assets/images/sty2.png',
      'assets/images/sty3.png',
      'assets/images/sty4.png',]),
    Product(
        6,
        'LMicro braids',
        'Brown Braid',
        'Of all the different types of braids for Black women, this braiding style may not look much like a braid at all. In contrast to the varying thickness of cornrows and box braids, micro braids are always created using very small sections of hair. This results in plaits that look and feel more like a thick strand of hair rather than interlaced braids. ',
        'assets/images/sty12.png',
        500,
        1,200, [ 'assets/images/sty10.png',
      'assets/images/sty12.png',
      'assets/images/sty3.png',
      'assets/images/sty4.png',]),
    Product(
        6,
        'Fulani braids',
        'Brown Braid',
        'Fulani braids are one of many tribal African braid styles that have become more mainstream. These are characterized by just one straight-back braid paired with others that flow in opposite directions across the crown of your head, often toward your ears or temples. The intricacy and beauty of this look make it one of the more popular styles of braids for Black women. Another appealing detail of Fulani braids is the combination of scalp-hugging cornrows on the top and the volumizing effect of box braids in the back. Feel free to get creative with this style by adding curls, extensions, or a pop of brightly colored beads. ',
        'assets/images/sty13.png',
        500,
        1,360,[ 'assets/images/sty1.png',
      'assets/images/sty2.png',
      'assets/images/sty3.png',
      'assets/images/sty4.png',])
  ];
  static List<Product> nigerianBraid = [
    Product(
        1,
        'Boho stitch braids',
        'Latest style',
        'This hairstyle is a combination of boho and stitch braids. Think of it as an extra way of rocking stitch braids.',
        'assets/images/sty14.png',
        200.0,
        1,190, [ 'assets/images/caro8.png',
      'assets/images/caro9.png',
      'assets/images/caro9.png',
      'assets/images/caro10.png',]),
    Product(
        2,
        'Cornrows',
        'Coloring trends',
        'Cornrows are a lifesaver, especially when you don’t want to do too much with your hair. You can even do it yourself if you have the time.',
        'assets/images/sty10.png',
        500,
        1,340, [ 'assets/images/caro8.png',
      'assets/images/caro9.png',
      'assets/images/caro9.png',
      'assets/images/caro10.png',]),
    Product(
        3,
        'Bantu knots with curls',
        'Nigerian cut',
        'Bantu knots has been around for a while and is always a hit.',
        'assets/images/sty12.png',
        300,
        0,280,[ 'assets/images/caro1.png',
      'assets/images/caro.png',
      'assets/images/caro2.png',
      'assets/images/caro3.png',]),
    Product(
        4,
        'Two-row cornrows',
        'Brown girl',
        'Before you roll your eyes and ask, “Cornrows again?” Listen, cornrows are simple, affordable, classy and versatile. They also don’t look like your regular cornrows.',
        'assets/images/sty9.png',
        350,
        1,230,[ 'assets/images/caro1.png',
      'assets/images/caro3.png',
      'assets/images/caro2.png',
      'assets/images/caro.png',]),
    Product(
        5,
        'Zigzag braids with beads',
        'Eygtiant Queen',
        'The curls give a fresh breath of life to hairstyles that would have been better left in 2000 and this ZigZag braid is proof.',
        'assets/images/sty9.png',
        390,
        1,300, [ 'assets/images/saudi.png',
      'assets/images/saudi1.png',
      'assets/images/saudi4.png',
      'assets/images/saudi3.png',]),
    Product(
        6,
        'Starter locs',
        'Brown Braid',
        'For when you’re just starting on your loc journey.',
        'assets/images/sty11.png',
        500,
        1,200, [ 'assets/images/sty8.png',
      'assets/images/sty9.png',
      'assets/images/sty12.png',
      'assets/images/sty10.png',]),
    Product(
        7,
        'Bantu locs',
        'Brown Braid',
        'Who says you can’t rock your bantu knots because your hair is locked? ',
        'assets/images/sty14.png',
        500,
        1,450, [ 'assets/images/caro8.png',
      'assets/images/caro1.png',
      'assets/images/caro2.png',
      'assets/images/caro10.png',])
  ];
}
