// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADo7uO81lYuQ3I55xwMg2AJEYXAxKX-r8',
    appId: '1:262123330851:web:a50e5e9f1fd7244ef5c096',
    messagingSenderId: '262123330851',
    projectId: 'my-e-commerce-fbe30',
    authDomain: 'my-e-commerce-fbe30.firebaseapp.com',
    storageBucket: 'my-e-commerce-fbe30.appspot.com',
    measurementId: 'G-GM9393XKVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACzLZiS7H6qFiB39hRoCDlnnvlWRvnNA',
    appId: '1:262123330851:android:15e66ef2d0204fdbf5c096',
    messagingSenderId: '262123330851',
    projectId: 'my-e-commerce-fbe30',
    storageBucket: 'my-e-commerce-fbe30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfuYmyYQU5xob9PPvLhzrtkg7uWIJR5ro',
    appId: '1:262123330851:ios:5f016782305c8b9ef5c096',
    messagingSenderId: '262123330851',
    projectId: 'my-e-commerce-fbe30',
    storageBucket: 'my-e-commerce-fbe30.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfuYmyYQU5xob9PPvLhzrtkg7uWIJR5ro',
    appId: '1:262123330851:ios:5f016782305c8b9ef5c096',
    messagingSenderId: '262123330851',
    projectId: 'my-e-commerce-fbe30',
    storageBucket: 'my-e-commerce-fbe30.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADo7uO81lYuQ3I55xwMg2AJEYXAxKX-r8',
    appId: '1:262123330851:web:c97982370b877a37f5c096',
    messagingSenderId: '262123330851',
    projectId: 'my-e-commerce-fbe30',
    authDomain: 'my-e-commerce-fbe30.firebaseapp.com',
    storageBucket: 'my-e-commerce-fbe30.appspot.com',
    measurementId: 'G-9K67ZHV96Y',
  );
}
